// <auto-generated />
using CustomerInfo.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CustomerInfo.Migrations
{
    [DbContext(typeof(CustomersContext))]
    [Migration("20180818170044_initialcreate")]
    partial class initialcreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.1-rtm-30846");

            modelBuilder.Entity("CustomerInfo.Models.Customer", b =>
                {
                    b.Property<int>("CustomerID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Company");

                    b.Property<string>("EmailAddress");

                    b.Property<string>("Gender");

                    b.Property<string>("GivenName");

                    b.Property<string>("MiddleInitial");

                    b.Property<string>("Occupation");

                    b.Property<string>("Surname");

                    b.Property<string>("Title");

                    b.HasKey("CustomerID");

                    b.ToTable("Customers");
                });
#pragma warning restore 612, 618
        }
    }
}
